#!/usr/bin/env python3
"""Sync blog posts from the pckt.blog RSS feed into assets/data/blog.js.

Runs in CI (see .github/workflows/sync-blog.yml). Uses only the Python
standard library so there is nothing to install. The output is a tiny JS
file that sets `window.blogPosts`; the blog page includes it with a plain
<script> tag, so it works on the live server AND when the site is opened
directly via file:// (where fetch() is blocked). The feed itself only has
to be read here, in CI — never from the browser (it has no CORS headers).
"""

import json
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from email.utils import parsedate_to_datetime
from pathlib import Path

FEED_URL = "https://nhull.pckt.blog/feed"
OUT_PATH = Path(__file__).resolve().parent.parent / "assets" / "data" / "blog.js"
DESC_MAX = 220

_TAG_RE = re.compile(r"<[^>]+>")
_WS_RE = re.compile(r"\s+")


def clean(text: str) -> str:
    """Strip HTML tags and collapse whitespace."""
    text = _TAG_RE.sub("", text or "")
    return _WS_RE.sub(" ", text).strip()


def excerpt(text: str, limit: int = DESC_MAX) -> str:
    text = clean(text)
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0].rstrip(".,;:—- ")
    return f"{cut} …"


def iso_date(pubdate: str) -> str:
    try:
        return parsedate_to_datetime(pubdate).date().isoformat()
    except (TypeError, ValueError):
        return ""


def fetch_feed(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "nhull.eu blog sync"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def parse(xml_text: str) -> list[dict]:
    root = ET.fromstring(xml_text)
    channel = root.find("channel")
    posts = []
    for item in channel.findall("item"):
        title = clean(item.findtext("title", ""))
        link = (item.findtext("link", "") or "").strip()
        if not title or not link:
            continue
        posts.append({
            "title": title,
            "url": link,
            "date": iso_date(item.findtext("pubDate", "")),
            "desc": excerpt(item.findtext("description", "")),
        })
    # Newest first.
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def main() -> int:
    posts = parse(fetch_feed(FEED_URL))
    if not posts:
        print("No posts parsed from feed; leaving blog.js untouched.", file=sys.stderr)
        return 1
    payload = json.dumps(posts, ensure_ascii=False, indent=2)
    OUT_PATH.write_text(
        "// Generated by scripts/sync_blog.py from https://nhull.pckt.blog/feed — do not edit by hand.\n"
        f"window.blogPosts = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(posts)} posts to {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
